### ISSUE TITLE
Stats Page Enhancements

### ISSUE THREAD

**Issue by jakesadie** [rschoen/fireworks-client#58]
- [ ] Allow for toggle of showing individual player distribution versus overall distribution based on current filters
- [ ] Allow for tables to be sorted (descending order) by whichever column header is selected - default columns are Games and Moves
- [ ] Align all tables and graphs to be same width on page
- [ ] Reduce number of major gridlines shown on horizontal axis from 15 (current) to 10, or even 6, in order to limit how many labels pop up on the horizontal axis
- [ ] If possible, apply some logic to max height of vertical axis - should be closest multiple of 5 above current max score; keep major gridlines on vertical axis as 5
- [ ] Set font size such that all column widths (typically determined by column title) are the same
- [ ] Reduce font size of parenthetical percent indicators
- [ ] Remove as many lines on the charts as possible - recommend only a line underneath column titles and to the right of row names
- [ ] Change "Overall" to "All" and highlight background of this row only

**Comment by rschoen** [comment]
I'm gonna need you to file these as separate bugs kthx

**Comment by jakesadie** [comment]
Ryan is a jerk
