### ISSUE TITLE
Add option to delete a current game

### ISSUE THREAD

**Issue by jakesadie** [rschoen/fireworks-client#78]

**Comment by rschoen** [comment]
This is in progress
<img width="224" alt="Screenshot 2023-11-23 134835" src="https://github.com/rschoen/fireworks-client/assets/3644011/84a6b10d-8ac4-4a51-b3a9-420176a356d6">

**Comment by rschoen** [comment]
You can now delete a game as long as players haven't all taken a turn yet (i.e. the first round of turns has not completed).
